/** 100 blog konusu — published: true olanlar detay sayfasına sahip */
export type BlogTopic = {
  slug: string;
  cluster: string;
  published: boolean;
  titles: { tr: string; en: string; ru: string; ar: string };
};

const clusters = {
  baski: "3D Baskı",
  tarama: "3D Tarama",
  mimari: "Mimari",
  otomotiv: "Otomotiv",
  prototip: "Prototip",
  yerel: "KKTC",
  rehber: "Rehber",
} as const;

function topic(
  slug: string,
  cluster: keyof typeof clusters,
  tr: string,
  en: string,
  published = false
): BlogTopic {
  return {
    slug,
    cluster: clusters[cluster],
    published,
    titles: { tr, en, ru: en, ar: en },
  };
}

export const BLOG_TOPICS: BlogTopic[] = [
  topic("3d-printer-ile-neler-yapilir", "baski", "3D printer ile neler yapılır?", "What can you do with a 3D printer?", true),
  topic("pla-abs-petg-farki", "baski", "PLA ABS PETG farkı nedir?", "PLA vs ABS vs PETG", true),
  topic("3d-baski-maliyeti-kktc", "yerel", "KKTC'de 3D baskı maliyeti", "3D printing cost in TRNC", true),
  topic("hizli-3d-baski-sure", "baski", "Hızlı 3D baskı kaç saatte?", "How fast is 3D printing?", true),
  topic("3d-tarama-nasil-yapilir", "tarama", "3D tarama nasıl yapılır?", "How does 3D scanning work?", true),
  topic("mimari-maket-uretimi-kktc", "mimari", "Mimari maket üretimi KKTC", "Architectural models TRNC", true),
  topic("arac-yedek-parca-3d-baski", "otomotiv", "Araç yedek parça 3D baskı", "3D printed car spare parts", true),
  topic("endustriyel-prototipleme-nedir", "prototip", "Endüstriyel prototipleme nedir?", "What is industrial prototyping?", true),
  topic("stl-obj-3mf-farki", "rehber", "STL OBJ 3MF farkı", "STL vs OBJ vs 3MF", true),
  topic("lefkosa-3d-baski-rehberi", "yerel", "Lefkoşa 3D baskı rehberi", "Nicosia 3D printing guide", true),
  topic("girne-3d-tarama-hizmeti", "yerel", "Girne 3D tarama hizmeti", "Kyrenia 3D scanning", true),
  topic("kapida-odeme-3d-siparis-kktc", "yerel", "Kapıda ödeme ile 3D sipariş KKTC", "Cash on delivery 3D orders", true),
  topic("3d-baski-hatalari", "baski", "3D baskıda 10 yaygın hata", "10 common 3D print failures", false),
  topic("renkli-3d-baski", "baski", "Renkli 3D baskı mümkün mü?", "Multi-color 3D printing", false),
  topic("katman-yuksekligi-secimi", "baski", "Katman yüksekliği nasıl seçilir?", "Layer height guide", false),
  topic("doluluk-orani-ne-olmali", "baski", "Doluluk oranı ne olmalı?", "Infill percentage guide", false),
  topic("tpu-esnek-parca-baski", "baski", "TPU ile esnek parça baskı", "Flexible TPU printing", false),
  topic("mini-figur-3d-baski", "baski", "Mini figür 3D baskı", "Miniature figure printing", false),
  topic("hediye-3d-baski-fikirleri", "baski", "Hediye için 3D baskı fikirleri", "3D printed gift ideas", false),
  topic("3d-baski-icin-model-hazirlama", "rehber", "3D baskı için model hazırlama", "Preparing models for print", false),
  topic("slicer-programi-ayarlari", "rehber", "Slicer ayarları başlangıç", "Slicer settings for beginners", false),
  topic("3d-yazici-bakim-rehberi", "rehber", "3D yazıcı bakım rehberi", "3D printer maintenance", false),
  topic("filament-nem-alma-cozumu", "baski", "Filament nem alma çözümü", "Wet filament solutions", false),
  topic("3d-baski-sonrası-zımpara", "baski", "3D baskı sonrası zımpara", "Post-processing sanding", false),
  topic("baski-destegi-kaldirma", "baski", "Baskı desteği kaldırma ipuçları", "Support removal tips", false),
  topic("el-tipi-tarayici-nedir", "tarama", "El tipi tarayıcı nedir?", "What is a handheld scanner?", false),
  topic("3d-tarama-hassasiyeti", "tarama", "3D tarama hassasiyeti", "3D scanning accuracy", false),
  topic("renkli-doku-tarama", "tarama", "Renkli doku tarama", "Color texture scanning", false),
  topic("saha-taramasi-avantajlari", "tarama", "Saha taraması avantajları", "On-site scanning benefits", false),
  topic("tersine-muhendislik-3d", "tarama", "Tersine mühendislik ve 3D", "Reverse engineering 3D", false),
  topic("buyuk-obje-tarama", "tarama", "Büyük obje tarama", "Large object scanning", false),
  topic("kultur-varligi-dijitallestirme", "tarama", "Kültür varlığı dijitalleştirme", "Heritage digitization", false),
  topic("3d-tarama-sonrasi-baski", "tarama", "Tarama sonrası baskı süreci", "Scan to print workflow", false),
  topic("ply-formati-nedir", "rehber", "PLY formatı nedir?", "What is PLY format?", false),
  topic("mimari-sunum-maketi", "mimari", "Mimari sunum maketi", "Presentation architectural models", false),
  topic("olcekli-maket-olculeri", "mimari", "Ölçekli maket ölçüleri", "Scale model ratios", false),
  topic("universite-maket-projesi", "mimari", "Üniversite maket projesi", "University model projects", false),
  topic("ic-mimari-maket-baski", "mimari", "İç mimari maket baskı", "Interior design models", false),
  topic("restorasyon-maketi-3d", "mimari", "Restorasyon maketi 3D", "Restoration scale models", false),
  topic("otomotiv-plastik-klips", "otomotiv", "Otomotiv plastik klips üretimi", "Automotive clip printing", false),
  topic("motosiklet-parca-baski", "otomotiv", "Motosiklet parça baskı", "Motorcycle part printing", false),
  topic("dashboard-parca-yenileme", "otomotiv", "Dashboard parça yenileme", "Dashboard part replacement", false),
  topic("klasik-arac-parca-uretim", "otomotiv", "Klasik araç parça üretim", "Classic car parts", false),
  topic("rv-karavan-parca-baski", "otomotiv", "Karavan parça baskı", "RV part printing", false),
  topic("mvp-uretim-3d", "prototip", "MVP üretim ile 3D", "MVP production with 3D", false),
  topic("urun-test-parcasi", "prototip", "Ürün test parçası", "Product test parts", false),
  topic("kalite-kontrol-fikstur", "prototip", "Kalite kontrol fikstürü", "QC fixtures", false),
  topic("ergonomi-prototipi", "prototip", "Ergonomi prototipi", "Ergonomic prototypes", false),
  topic("seri-uretim-oncesi-3d", "prototip", "Seri üretim öncesi 3D", "Pre-mass production 3D", false),
  topic("gazimagusa-3d-baski", "yerel", "Gazimağusa 3D baskı", "Famagusta 3D printing", false),
  topic("guzelyurt-3d-hizmet", "yerel", "Güzelyurt 3D hizmet", "Morphou 3D services", false),
  topic("iskele-prototip-uretim", "yerel", "İskele prototip üretim", "Trikomo prototyping", false),
  topic("kibris-3d-printing-ingilizce", "yerel", "Cyprus 3D printing English", "3D printing Cyprus English", false),
  topic("kktc-maker-projeleri", "yerel", "KKTC maker projeleri", "TRNC maker projects", false),
  topic("universite-3d-laboratuvar", "yerel", "Üniversite 3D laboratuvar", "University 3D lab", false),
  topic("final3d-vs-online-baski", "rehber", "Yerel vs online 3D baskı", "Local vs online 3D print", false),
  topic("3d-baski-guvenlik", "rehber", "3D baskı güvenliği", "3D printing safety", false),
  topic("gida-guvenligi-3d-baski", "rehber", "Gıda güvenliği ve 3D baskı", "Food safe 3D printing", false),
  topic("medikal-3d-baski-uyari", "rehber", "Medikal 3D baskı uyarıları", "Medical 3D printing notes", false),
  topic("cosplay-parca-uretim", "baski", "Cosplay parça üretim", "Cosplay part production", false),
  topic("oyuncak-3d-baski", "baski", "Oyuncak 3D baskı", "Toy 3D printing", false),
  topic("drone-parca-baski", "baski", "Drone parça baskı", "Drone part printing", false),
  topic("elektronik-kutu-uretim", "baski", "Elektronik kutu üretim", "Electronics enclosure print", false),
  topic("robotik-parca-prototip", "prototip", "Robotik parça prototip", "Robotics prototypes", false),
  topic("denizcilik-parca-baski", "otomotiv", "Denizcilik parça baskı", "Marine part printing", false),
  topic("tarim-ekipman-parca", "prototip", "Tarım ekipman parça", "Agriculture equipment parts", false),
  topic("mobilya-prototip-3d", "mimari", "Mobilya prototip 3D", "Furniture prototypes", false),
  topic("ayakkabi-kaliplari-3d", "prototip", "Ayakkabı kalıpları 3D", "Shoe last 3D", false),
  topic("takı-kaliplari-baski", "baski", "Takı kalıpları baskı", "Jewelry mold printing", false),
  topic("sanat-heykelleri-3d", "baski", "Sanat heykelleri 3D", "Art sculpture 3D", false),
  topic("muzee-arşiv-tarama", "tarama", "Müze arşiv tarama", "Museum archive scanning", false),
  topic("dental-model-uyari", "rehber", "Dental model uyarı", "Dental model disclaimer", false),
  topic("karbon-fiber-infill-mit", "rehber", "Karbon fiber infill miti", "Carbon fiber infill myth", false),
  topic("abs-baski-kapali-alan", "baski", "ABS baskı kapalı alan", "ABS enclosed printing", false),
  topic("petg-dis-mekan", "baski", "PETG dış mekan dayanımı", "PETG outdoor durability", false),
  topic("3d-baski-fiyat-hesaplama", "baski", "3D baskı fiyat hesaplama", "3D print price calculation", false),
  topic("whatsapp-teklif-sureci", "yerel", "WhatsApp teklif süreci", "WhatsApp quote process", false),
  topic("3d-tarama-fiyat-kktc", "yerel", "3D tarama fiyat KKTC", "3D scan pricing TRNC", false),
  topic("prototip-vs-uretim", "prototip", "Prototip vs seri üretim", "Prototype vs production", false),
  topic("cad-yazilim-secimi", "rehber", "CAD yazılım seçimi", "Choosing CAD software", false),
  topic("fusion-360-3d-baski", "rehber", "Fusion 360'dan baskıya", "Fusion 360 to print", false),
  topic("blender-3d-baski", "rehber", "Blender'dan 3D baskı", "Blender for 3D print", false),
  topic("mesh-onarma-ipuclari", "tarama", "Mesh onarım ipuçları", "Mesh repair tips", false),
  topic("3d-baski-malzeme-secimi", "baski", "Malzeme seçim rehberi", "Material selection guide", false),
  topic("isletmeler-icin-3d", "prototip", "İşletmeler için 3D", "3D for businesses", false),
  topic("startup-mvp-kktc", "yerel", "Startup MVP KKTC", "Startup MVP TRNC", false),
  topic("otel-dekor-3d-parca", "mimari", "Otel dekor 3D parça", "Hotel decor 3D parts", false),
  topic("reklam-standi-3d", "baski", "Reklam standı 3D baskı", "Ad stand 3D print", false),
  topic("ozel-hediye-kutusu", "baski", "Özel hediye kutusu", "Custom gift boxes", false),
  topic("3d-baski-ile-maket-karsilastirma", "mimari", "3D baskı vs el yapımı maket", "3D print vs handmade", false),
  topic("scan-to-cad-workflow", "tarama", "Scan to CAD iş akışı", "Scan to CAD workflow", false),
  topic("lazer-vs-3d-karsilastirma", "rehber", "Lazer kesim vs 3D", "Laser vs 3D comparison", false),
  topic("cnc-vs-3d-ne-zaman", "rehber", "CNC vs 3D ne zaman?", "When CNC vs 3D?", false),
  topic("3d-baski-gelecek-kktc", "yerel", "KKTC'de 3D geleceği", "Future of 3D in TRNC", false),
  topic("ogrenci-projesi-indirim", "yerel", "Öğrenci projesi destek", "Student project support", false),
  topic("maker-faire-kktc", "yerel", "Maker etkinlikleri KKTC", "Maker events TRNC", false),
  topic("3d-baski-sozlugu", "rehber", "3D baskı sözlüğü", "3D printing glossary", false),
  topic("featured-snippet-3d-nedir", "rehber", "3D baskı nedir?", "What is 3D printing?", false),
  topic("ai-3d-model-uretim", "rehber", "AI ile 3D model", "AI 3D models", false),
  topic("surdurulebilir-3d-baski", "rehber", "Sürdürülebilir 3D baskı", "Sustainable 3D printing", false),
  topic("geri-donusum-filament", "rehber", "Geri dönüşüm filament", "Recycled filament", false),
  topic("3d-baski-atolyesi-kurma", "rehber", "3D atölye kurma", "Starting a 3D workshop", false),
  topic("final3d-hizmet-ozeti", "yerel", "FINAL3D hizmet özeti", "FINAL3D services overview", false),
];

export const PUBLISHED_BLOG_SLUGS = BLOG_TOPICS.filter((t) => t.published).map(
  (t) => t.slug
);
