import type { Locale } from "@/i18n/config";
import { pickLocale } from "@/lib/seo/content/pick-locale";
import type { LocalizedSeoPage, SeoPageContent } from "@/lib/seo/types";

const services: Record<string, LocalizedSeoPage> = {
  "3d-baski": {
    tr: {
      path: "/hizmetler/3d-baski",
      metaTitle: "3D Baskı Hizmeti KKTC",
      metaDescription: "FDM 3D baskı: özel parça, prototip, PLA ABS PETG TPU.",
      h1: "3D Baskı Hizmeti",
      intro: "Endüstriyel kalitede filament baskı ile parçanızı üretiyoruz.",
      sections: [{ heading: "Süreç", body: "Dosya inceleme → üretim → kalite kontrol → teslimat." }],
      faq: [{ question: "Minimum kalınlık?", answer: "Parça geometrisine göre 1–2 mm duvar öneriyoruz." }],
      cta: { href: "/ozel-baski#talep-form", label: "Teklif Al" },
      related: [{ href: "/3d-baski-kktc", label: "3D baskı KKTC hub" }],
    },
    en: {
      path: "/hizmetler/3d-baski",
      metaTitle: "3D Printing Service TRNC",
      metaDescription: "FDM printing for custom parts and prototypes.",
      h1: "3D Printing Service",
      intro: "Production-grade FDM printing for your parts.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Get quote" },
      related: [{ href: "/3d-baski-kktc", label: "3D printing hub" }],
    },
    ru: {
      path: "/hizmetler/3d-baski",
      metaTitle: "Услуга 3D-печати",
      metaDescription: "FDM-печать деталей.",
      h1: "3D-печать",
      intro: "Печать филаментом.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Расчёт" },
      related: [],
    },
    ar: {
      path: "/hizmetler/3d-baski",
      metaTitle: "خدمة الطباعة ثلاثية الأبعاد",
      metaDescription: "طباعة FDM.",
      h1: "طباعة 3D",
      intro: "طباعة بالفلامنت.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "عرض سعر" },
      related: [],
    },
  },
  "3d-tarama": {
    tr: {
      path: "/hizmetler/3d-tarama",
      metaTitle: "3D Tarama Hizmeti",
      metaDescription: "El tipi tarayıcı, mesh hazırlık, renkli doku.",
      h1: "3D Tarama Hizmeti",
      intro: "Nesnelerinizi yüksek çözünürlüklü dijital modele çeviriyoruz.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Tarama Teklifi" },
      related: [{ href: "/3d-tarama-kktc", label: "3D tarama hub" }],
    },
    en: {
      path: "/hizmetler/3d-tarama",
      metaTitle: "3D Scanning Service",
      metaDescription: "Handheld scanning and mesh delivery.",
      h1: "3D Scanning Service",
      intro: "High-resolution digitization of your objects.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Scan quote" },
      related: [],
    },
    ru: {
      path: "/hizmetler/3d-tarama",
      metaTitle: "3D-сканирование",
      metaDescription: "Услуга сканирования.",
      h1: "3D-сканирование",
      intro: "Оцифровка объектов.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Заявка" },
      related: [],
    },
    ar: {
      path: "/hizmetler/3d-tarama",
      metaTitle: "خدمة المسح ثلاثي الأبعاد",
      metaDescription: "مسح يدوي.",
      h1: "مسح 3D",
      intro: "رقمنة الأجسام.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "عرض سعر" },
      related: [],
    },
  },
  "prototip-uretim": {
    tr: {
      path: "/hizmetler/prototip-uretim",
      metaTitle: "Prototip Üretim",
      metaDescription: "Hızlı test parçası ve MVP üretimi.",
      h1: "Prototip Üretim",
      intro: "Tasarım doğrulama için hızlı baskı.",
      sections: [],
      faq: [],
      cta: { href: "/prototip-uretim-kibris", label: "Prototip hub" },
      related: [],
    },
    en: {
      path: "/hizmetler/prototip-uretim",
      metaTitle: "Prototype Production",
      metaDescription: "Fast MVP parts.",
      h1: "Prototype Production",
      intro: "Quick printed test parts.",
      sections: [],
      faq: [],
      cta: { href: "/prototip-uretim-kibris", label: "Prototyping hub" },
      related: [],
    },
    ru: {
      path: "/hizmetler/prototip-uretim",
      metaTitle: "Прототипирование",
      metaDescription: "Быстрые прототипы.",
      h1: "Прототипы",
      intro: "Тестовые детали.",
      sections: [],
      faq: [],
      cta: { href: "/prototip-uretim-kibris", label: "Хаб" },
      related: [],
    },
    ar: {
      path: "/hizmetler/prototip-uretim",
      metaTitle: "إنتاج نماذج أولية",
      metaDescription: "نماذج سريعة.",
      h1: "نماذج أولية",
      intro: "قطع اختبار.",
      sections: [],
      faq: [],
      cta: { href: "/prototip-uretim-kibris", label: "المركز" },
      related: [],
    },
  },
  "mimari-maket": {
    tr: {
      path: "/hizmetler/mimari-maket",
      metaTitle: "Mimari Maket 3D Baskı KKTC",
      metaDescription: "Ölçekli mimari maket ve sunum modelleri.",
      h1: "Mimari Maket Üretimi",
      intro: "Mimarlık öğrencileri ve ofisler için hassas ölçekli maketler.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Maket Teklifi" },
      related: [{ href: "/3d-baski-kktc", label: "3D baskı" }],
    },
    en: {
      path: "/hizmetler/mimari-maket",
      metaTitle: "Architectural Model 3D Print",
      metaDescription: "Scale models for presentations.",
      h1: "Architectural Models",
      intro: "Scale models for studios and students.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Get quote" },
      related: [],
    },
    ru: {
      path: "/hizmetler/mimari-maket",
      metaTitle: "Архитектурные макеты",
      metaDescription: "3D-печать макетов.",
      h1: "Архитектурные макеты",
      intro: "Макеты в масштабе.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Расчёт" },
      related: [],
    },
    ar: {
      path: "/hizmetler/mimari-maket",
      metaTitle: "نماذج معمارية",
      metaDescription: "طباعة نماذج معمارية.",
      h1: "نماذج معمارية",
      intro: "نماذج بمقياس.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "عرض سعر" },
      related: [],
    },
  },
  "yedek-parca-uretimi": {
    tr: {
      path: "/hizmetler/yedek-parca-uretimi",
      metaTitle: "Yedek Parça 3D Baskı",
      metaDescription: "Kırık plastik parça ve otomotiv yedek parça üretimi.",
      h1: "Yedek Parça Üretimi",
      intro: "Tersine mühendislik veya ölçümle yedek parça üretiyoruz.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Tarama + Üretim" },
      related: [],
    },
    en: {
      path: "/hizmetler/yedek-parca-uretimi",
      metaTitle: "Spare Parts 3D Printing",
      metaDescription: "Replacement plastic and automotive parts.",
      h1: "Spare Part Production",
      intro: "Reverse engineering and printed replacements.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Scan + print" },
      related: [],
    },
    ru: {
      path: "/hizmetler/yedek-parca-uretimi",
      metaTitle: "Запчасти 3D-печатью",
      metaDescription: "Изготовление запчастей.",
      h1: "Запчасти",
      intro: "Реверс-инжиниринг и печать.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "Заявка" },
      related: [],
    },
    ar: {
      path: "/hizmetler/yedek-parca-uretimi",
      metaTitle: "قطع غيار بالطباعة 3D",
      metaDescription: "إنتاج قطع بديلة.",
      h1: "قطع الغيار",
      intro: "هندسة عكسية وطباعة.",
      sections: [],
      faq: [],
      cta: { href: "/3d-tarama/teklif", label: "مسح + طباعة" },
      related: [],
    },
  },
  "endustriyel-uretim": {
    tr: {
      path: "/hizmetler/endustriyel-uretim",
      metaTitle: "Endüstriyel 3D Üretim KKTC",
      metaDescription: "Fonksiyonel prototip ve küçük seri üretim.",
      h1: "Endüstriyel Üretim",
      intro: "Test ve kalite doğrulama için dayanıklı malzeme seçenekleri.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "B2B Teklif" },
      related: [],
    },
    en: {
      path: "/hizmetler/endustriyel-uretim",
      metaTitle: "Industrial 3D Production",
      metaDescription: "Functional prototypes and small batches.",
      h1: "Industrial Production",
      intro: "Durable materials for validation parts.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "B2B quote" },
      related: [],
    },
    ru: {
      path: "/hizmetler/endustriyel-uretim",
      metaTitle: "Промышленная 3D-печать",
      metaDescription: "Промышленные детали.",
      h1: "Промышленное производство",
      intro: "Прототипы и малые серии.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "B2B" },
      related: [],
    },
    ar: {
      path: "/hizmetler/endustriyel-uretim",
      metaTitle: "إنتاج صناعي 3D",
      metaDescription: "إنتاج وظيفي.",
      h1: "إنتاج صناعي",
      intro: "قطع للاختبار.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "عرض B2B" },
      related: [],
    },
  },
  "kisisel-uretim": {
    tr: {
      path: "/hizmetler/kisisel-uretim",
      metaTitle: "Kişiye Özel 3D Üretim",
      metaDescription: "Hediye, figür ve kişisel tasarım baskısı.",
      h1: "Kişiye Özel Üretim",
      intro: "Figür, hediye ve özel tasarım parçalarınızı basıyoruz.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Tasarım Gönder" },
      related: [],
    },
    en: {
      path: "/hizmetler/kisisel-uretim",
      metaTitle: "Personalized 3D Production",
      metaDescription: "Gifts, figures and custom designs.",
      h1: "Personal Production",
      intro: "Custom gifts and figurines.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Send design" },
      related: [],
    },
    ru: {
      path: "/hizmetler/kisisel-uretim",
      metaTitle: "Персональная 3D-печать",
      metaDescription: "Подарки и фигурки.",
      h1: "Персональное производство",
      intro: "Индивидуальные изделия.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "Заявка" },
      related: [],
    },
    ar: {
      path: "/hizmetler/kisisel-uretim",
      metaTitle: "إنتاج شخصي 3D",
      metaDescription: "هدايا وتماثيل.",
      h1: "إنتاج شخصي",
      intro: "تصاميم مخصصة.",
      sections: [],
      faq: [],
      cta: { href: "/ozel-baski#talep-form", label: "إرسال" },
      related: [],
    },
  },
};

export function getServicePage(slug: string, locale: Locale): SeoPageContent | null {
  const page = services[slug];
  if (!page) return null;
  return pickLocale(page, locale);
}

export function getAllServiceSlugs() {
  return Object.keys(services);
}
